jobs:
  - script: >
      pipelineJob('paramtestjob') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                parameters {
                  stringParam('deployment_file_name', 'deploy.yaml', 'my description')
                }
                environmentVariables{
                  deployment_name='\${params.deployment_file_name}'
                }
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                      echo "${deployment_name}"
                    }
                  }
                }
              }""".stripIndent())
          }   
        }
      }
