jobs:
  - script: >
      pipelineJob('paramtestjob') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                parameters {
                  string(name:'deployment_file_name', defaultValue: 'deploy.yaml', description: 'kubernetes deployment file')
                }
                environment{
                  deployment_name='\${params.deployment_file_name}'
                }
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                      echo "${deployment_name}"
                    }
                  }
                }
              }""".stripIndent())
          }   
        }
      }
